config_path: ~/PROC/shared/config
font_path: [/home/pi/PROC/shared/dmd]
pinproc_class: procgame.fakepinproc.FakePinPROC
keyboard_switch_map:
    # Enter, Up, Down, Exit
    3: SD3
    2: SD2
    1: SD1
    0: SD0
    # Start:
    s: 10
    z: SF4
    /: SF2
