config_path: ~/PROC/shared/config
font_path: [/home/pi/PROC/shared/dmd]
#pinproc_class: procgame.fakepinproc.FakePinPROC
keyboard_switch_map:
    # Enter, Up, Down, Exit
    #3: 14
    #2: 13
    #1: 12
    #0: SD0
    # Start:
    s: 18
    l: 17
    u: 100
    d: 101
    f: 102
    w: 103
    /: SF2
    q: 9
    p: 8
